data:
  config:
    sample_rate: &sample_rate 16000 #*sample_rate
  config_per_dataset_dict:
    dataset_name:
      preprocessor_class_meta_list: 
        - { 'name': 'Preprocessor', 'args': {}}
#####################################################################################################
pytorch_data:
  class_meta: { 'name' : 'PytorchDataLoader', 'args' : {}}
  dataloader:
    train:
      batch_size: 16
      num_workers: 15
      dataset: 
        class_meta: { 'name' : 'DataSet', 'args' : {}}
        dataset_load_on_memory: True
      batch_sampler:
        class_meta: { 'name' : '', 'args' : {}}
      collate_fn: True
    valid:
      batch_size: 16
      num_workers: 15
      dataset: 
        class_meta: { 'name' : 'DataSet', 'args' : {}}
      shuffle: False
      drop_last: True
#####################################################################################################
model:
  class_name: ''
  class_meta_dict:
    model_class_name: {}
#####################################################################################################
train:
  class_meta: { 'name' : 'Trainer', 'args' : {}}
  log_writer_class_name: 'LogWriter'
  save_model_after_epoch: 30
  save_model_every_epoch: 5

  optimizer_control_config:
    class_meta: { 'name' : 'OptimizerControl', 'args' : {}}

  optimizer: 
    name: "Adam"
    config: 
      lr: 1e-3
      eps: 1e-08
      weight_decay: 0.0
      amsgrad: True

  scheduler:
    name: "LambdaLR"
    interval: 'step' #epoch
    frequency: 1
    config: 
      warm_up_steps: 1000
      reduce_lr_steps: 15000

  loss_control:
    class_meta: { 'name' : 'LossControl', 'args' : {}}

  loss_dict:
    loss_name :
      pred_name: ''
      target_name: ''
      lossfunction: l1
      weight: 1
    
  loss_list_for_performance_comparison: 
    - loss_name
#####################################################################################################
inference:
  class_meta:
    name: 'Inferencer'
    args: {}
  pretrain_dir_name: ''
#####################################################################################################
evaluate:
  class_meta:
    name: 'Evaluater'
    args: 
      source_dir: ''